kyy119/BoothRock

src/main/webapp/NewFile.jsp
=> sync 테스트22

src/main/webapp/hello.jsp
=> login test

src/main/webapp/NewFile.jsp, src/main/webapp/wjtest.jsp
=> Mypage cus

src/main/java/com/multi/FM/users/Hello.java
=> login test2

src/main/java/com/multi/FM/booth/BoothContoller.java, src/main/java/com/multi/FM/report/BoothReportController.java
=> booth 패키지 생성 / 컨트롤러 임의 작성

src/main/java/com/multi/FM/booth/BoothContoller.java, src/main/java/com/multi/FM/myboothpage/BoothVO.java, src/main/java/com/multi/FM/myboothpage/MyBoothController.java
webapp, views 아래 각자 jsp 폴더 만들기
=> webapp, views 아래 각자 jsp 폴더 만들기

src/main/webapp/WEB-INF/views/boothpage/home.jsp, src/main/webapp/WEB-INF/views/fstv/home.jsp, src/main/webapp/WEB-INF/views/manager/home.jsp, src/main/webapp/WEB-INF/views/myboothpage/home.jsp, src/main/webapp/WEB-INF/views/mypage/home.jsp, src/main/webapp/WEB-INF/views/users/home.jsp, src/main/webapp/boothpage/home.jsp, src/main/webapp/fstv/home.jsp, src/main/webapp/manager/home.jsp, src/main/webapp/myboothpage/home.jsp, src/main/webapp/mypage/home.jsp, src/main/webapp/resources/home.jsp, src/main/webapp/users/home.jsp
webbapp, views 아래 각자 폴더 생성 및 테스트용 home.jsp 넣기
=> webbapp, views 아래 각자 폴더 생성 및 테스트용 home.jsp 넣기

src/main/java/com/multi/FM/users/SellerVO.java, src/main/java/com/multi/FM/users/SmsSend.java, src/main/java/com/multi/FM/users/UsersController.java, src/main/java/com/multi/FM/users/UsersDAO.java, src/main/java/com/multi/FM/users/UsersService.java, src/main/java/com/multi/FM/users/UsersVO.java, src/main/resources/mapper/users.xml, src/main/webapp/users/footer.jsp, src/main/webapp/users/header.jsp, src/main/webapp/users/signup.jsp, src/main/webapp/users/signup_num.jsp
=> Login 수정사항

src/main/java/com/multi/FM/booth/BoothDAO.java, src/main/java/com/multi/FM/users/SmsSend.java
=> BoothDao 클래스 명 소문자 오타 변경

src/main/java/com/multi/FM/booth/BoothDAO.java
=> BoothDAO 대소문자 변경

src/main/java/com/multi/FM/booth/BoothDAO.java, src/main/webapp/resources/css/fstv_list.css
fstv_list.css 제목 줄 간격, 찜버튼 위치 수정했습니다
=> FSTV fstv_list.css 수정

src/main/java/com/multi/FM/booth/BoothDAO.java
=> login : BoothDAO 이름고침

src/main/webapp/resources/js/main.js
=> FSTV main.css 배너 이미지 사이즈 조절 -완-

src/main/webapp/WEB-INF/views/create_account_consumer.jsp, src/main/webapp/WEB-INF/views/create_account_seller.jsp, src/main/webapp/resources/js/signup.js
=> login : 임시수정

src/main/webapp/mypage_jjim.jsp, src/main/webapp/resources/css/mypage_jjim.css, src/main/webapp/resources/js/mypage_jjim.js
=> 마이페이지 찜목록 하트 수정

src/main/java/com/multi/FM/booth/BoothContoller.java, src/main/java/com/multi/FM/booth/BoothDAO.java, src/main/java/com/multi/FM/booth/BoothProductVO.java, src/main/java/com/multi/FM/myboothpage/BoothVO.java, src/main/resources/mapper/boothMapper.xml, src/main/webapp/booth_detail.jsp
UI와 기능 연동 및 상세정보 조회 기능 개발
-BoothController 수정
-BoothProductVO 작성
-BoothVO 조인 칼럼 추가
=> [Feat]: "부스 상세정보 조회 기능 구현"

src/main/webapp/WEB-INF/views/create_account_consumer.jsp, src/main/webapp/WEB-INF/views/create_account_seller.jsp, src/main/webapp/header.jsp, src/main/webapp/resources/css/signup_type.css, src/main/webapp/resources/js/signup_cus.js, src/main/webapp/resources/js/signup_seller.js, src/main/webapp/signup_cus.jsp, src/main/webapp/signup_num.jsp, src/main/webapp/signup_seller.jsp, src/main/webapp/signup_type.jsp
=> Feat: "회원 가입 기능 구현"

src/main/webapp/admin_header.jsp, src/main/webapp/admin_main.jsp, src/main/webapp/booth_detail.jsp, src/main/webapp/booth_report.jsp, src/main/webapp/cs_ask.jsp, src/main/webapp/cs_question.jsp, src/main/webapp/fstv_list.jsp, src/main/webapp/resources/css/admin_header.css, src/main/webapp/resources/css/admin_main.css, src/main/webapp/resources/css/booth_report.css, src/main/webapp/resources/css/cs_ask.css, src/main/webapp/resources/css/cs_question.css, src/main/webapp/resources/css/fstv_list.css, src/main/webapp/resources/css/header.css, src/main/webapp/resources/js/cs_question.js
=> [add] 고객센터 및 관리자 메인 UI 제작

src/main/webapp/ban_list.jsp, src/main/webapp/resources/css/mypage_ask.css, src/main/webapp/resources/css/user_edit.css, src/main/webapp/resources/css/user_list.css, src/main/webapp/user_edit.jsp, src/main/webapp/user_list.jsp
=> [Add] 관리자 유저/밴 리스트 UI 제작

src/main/webapp/WEB-INF/views/fstv_detail.jsp, src/main/webapp/header.jsp
=> [Add] css 수정

src/main/java/com/multi/FM/users/UsersController.java, src/main/java/com/multi/FM/users/UsersDAO.java, src/main/java/com/multi/FM/users/UsersService.java, src/main/resources/mapper/users.xml, src/main/webapp/WEB-INF/views/find_id.jsp, src/main/webapp/find_id_num.jsp
=> Feat : "아이디찾기 구현"

src/main/java/com/multi/FM/users/SmsSend.java, src/main/webapp/resources/js/signup.js
=> Fix : "API키 임시로 삭제"

src/main/java/com/multi/FM/mypage/MypageController.java, src/main/webapp/WEB-INF/views/mypage_edit_info.jsp, src/main/webapp/mypage.jsp
- 비밀번호 유효성
-  전화번호 기존값과 동일 할 시 인증 생략
-  사용자별 부스관리탭 유무, 사업자 번호 입력창 유무
=> Feat : 회원정보수정 

src/main/java/com/multi/FM/users/SellerVO.java, src/main/java/com/multi/FM/users/UsersController.java, src/main/java/com/multi/FM/users/UsersDAO.java, src/main/java/com/multi/FM/users/UsersService.java, src/main/java/com/multi/FM/users/UsersVO.java, src/main/resources/mapper/users.xml, src/main/webapp/WEB-INF/views/edit_password.jsp, src/main/webapp/find_password_num.jsp, src/main/webapp/login.jsp, src/main/webapp/new_pw.jsp, src/main/webapp/resources/js/find_num.js, src/main/webapp/resources/js/new_pw.js
비밀번호 찾기 ui 제작 및 비밀번호 찾기(전화번호 인증 후 유저가 비밀번호 수정) 기능 구현
=> Feat : "비밀번호 찾기 구현"

src/main/webapp/WEB-INF/views/fstv_detail.jsp, src/main/webapp/resources/css/booth_detail.css, src/main/webapp/resources/css/booth_review.css, src/main/webapp/resources/css/fstv_detail.css, src/main/webapp/resources/js/fstv_detail.js
fstv / booth 실제 데이터에 따른 css 수정
=> Add: "fstv / booth 실제 데이터에 따른 css 수정"

src/main/webapp/new_pw.jsp, src/main/webapp/resources/js/new_pw.js, src/main/webapp/resources/js/signup_cus.js, src/main/webapp/resources/js/signup_seller.js, src/main/webapp/signup_cus.jsp, src/main/webapp/signup_seller.jsp
=> Fix : "회원가입,아이디/비밀번호찾기 alert 수정"

src/main/java/com/multi/FM/manager/ManagerController.java, src/main/java/com/multi/FM/manager/ReportDAO.java, src/main/java/com/multi/FM/manager/ReportVO.java, src/main/java/com/multi/FM/manager/package-info.java, src/main/resources/mapper/manager.xml, src/main/webapp/WEB-INF/views/report_list.jsp, src/main/webapp/report.jsp
=> Feat: "관리자 신고 리스트 구현"

src/main/webapp/agree.jsp, src/main/webapp/resources/css/signup.css, src/main/webapp/resources/js/new_pw.js, src/main/webapp/resources/js/signup_cus.js, src/main/webapp/resources/js/signup_seller.js, src/main/webapp/signup_cus.jsp, src/main/webapp/signup_seller.jsp
회원가입시 개인정보동의서 체크해야 가입 가능으로 기능 추가
=> Feat : "회원가입 - 개인정보동의서"

src/main/webapp/resources/css/booth_detail.css
=> Add: "tab 메뉴 css 수정"

src/main/java/com/multi/FM/mypage/MypageController.java, src/main/java/com/multi/FM/mypage/MypageDAO.java, src/main/java/com/multi/FM/users/UsersVO.java, src/main/resources/mapper/myPage.xml, src/main/webapp/WEB-INF/views/mypage_edit_info.jsp, src/main/webapp/WEB-INF/views/mypage_review.jsp, src/main/webapp/mypage.jsp, src/main/webapp/resources/js/mypage.js, src/main/webapp/resources/js/mypage_edit.js
=> Feat : 회원정보 수정 완료

src/main/webapp/WEB-INF/views/login.jsp, src/main/webapp/resources/js/signup_cus.js, src/main/webapp/resources/js/signup_seller.js
로그인 할때 조건불만족 이면 띄우는 alert 삭제,
뷰에 있는 로그인에서 블랙리스트 관련 notify가 빠져서 추가
=> Fix : "로그인 수정"

src/main/java/com/multi/FM/users/SmsSend.java, src/main/java/com/multi/FM/users/UsersController.java, src/main/java/com/multi/FM/users/UsersDAO.java, src/main/java/com/multi/FM/users/UsersService.java, src/main/resources/mapper/users.xml, src/main/webapp/WEB-INF/views/login.jsp, src/main/webapp/login.jsp
=> Fix : " 변수명 수정"

src/main/java/com/multi/FM/users/UsersController.java, src/main/java/com/multi/FM/users/UsersDAO.java, src/main/java/com/multi/FM/users/UsersService.java, src/main/resources/mapper/users.xml
=> Fix : "유저 블랙리스트 기능 구현"

src/main/java/com/multi/FM/report/BoothReportController.java, src/main/resources/mapper/boothMapper.xml, src/main/webapp/WEB-INF/views/booth_report.jsp, src/main/webapp/resources/js/booth_detail.js
신고버튼 클릭 시 loginCheck 오류부분 수정
Fixes : Insert 외래키오류 수정중
=> Fix : "신고기능 로그인여부 체크 오류 수정"

src/main/java/com/multi/FM/mypage/MypageController.java, src/main/java/com/multi/FM/mypage/MypageDAO.java, src/main/resources/mapper/myPage.xml, src/main/webapp/WEB-INF/views/mypage_ask.jsp, src/main/webapp/resources/css/mypage_ask_detail.css, src/main/webapp/resources/js/mypage_ask.js, src/main/webapp/resources/js/mypage_jjim.js
=> Feat : 마이페이지-문의내역조회,상세보기

src/main/java/com/multi/FM/report/BoothReportController.java, src/main/resources/mapper/boothMapper.xml, src/main/webapp/WEB-INF/views/booth_detail.jsp, src/main/webapp/WEB-INF/views/booth_report.jsp, src/main/webapp/resources/js/booth_detail.js
중복신고방지 기능 로직 변경, 오류 수정완료
report data insert 시 외래키 오류 수정완료
alert 노출 수정완료
=> Fix : "부스신고기능 오류 수정완료 "

src/main/resources/fstvdata/detail_info.xml, src/main/resources/fstvdata/fstvmain.xml
- tour API 데이터 업데이트에 따라 DB 업데이트 겸 xml 데이터 추가
=> Add: "축제 데이터 22건 추가"

src/main/java/com/multi/FM/manager/ManagerController.java, src/main/java/com/multi/FM/manager/ManagerDAO.java, src/main/java/com/multi/FM/manager/PagingVO.java, src/main/java/com/multi/FM/users/UsersVO.java, src/main/resources/mapper/manager.xml, src/main/webapp/WEB-INF/views/manager/ban_user_list.jsp, src/main/webapp/WEB-INF/views/manager/user_list.jsp, src/main/webapp/WEB-INF/views/users/login.jsp, src/main/webapp/fstv_list.jsp, src/main/webapp/fstv_map.jsp, src/main/webapp/header.jsp, src/main/webapp/manager/access_denied.jsp, src/main/webapp/manager/admin_header.jsp, src/main/webapp/manager/admin_main.jsp, src/main/webapp/resources/css/admin_header.css, src/main/webapp/resources/css/fstv_list.css, src/main/webapp/resources/css/header.css, src/main/webapp/resources/css/mypage_edit.css, src/main/webapp/resources/css/mypage_jjim.css
=> Feat: "관리자 유저 밴 리스트 페이지 구현"

src/main/java/com/multi/FM/users/SmsSend.java, src/main/java/com/multi/FM/users/UsersConfiguration.java, src/main/java/com/multi/FM/users/UsersController.java, src/main/resources/mapper/users.xml, src/main/webapp/header.jsp, src/main/webapp/resources/js/find_num.js, src/main/webapp/resources/js/signup_num.js, src/main/webapp/resources/js/signup_seller.js
=> Fix : "api키 properties로 빼기"

src/main/java/com/multi/FM/users/SmsSend.java, src/main/java/com/multi/FM/users/UsersController.java, src/main/webapp/resources/js/mypage_edit.js, src/main/webapp/resources/js/signup_num.js, src/main/webapp/resources/js/signup_seller.js
=> Fix : "api키 config로 빼기 2"

src/main/java/com/multi/FM/booth/BoothReviewContoller.java, src/main/java/com/multi/FM/booth/NaverOCR.java, src/main/java/com/multi/FM/booth/ReceiptService.java, src/main/java/com/multi/FM/booth/ReceiptVO.java, src/main/webapp/WEB-INF/views/review/booth_review.jsp, src/main/webapp/WEB-INF/views/review/booth_review_write.jsp, src/main/webapp/resources/js/booth_review_write.js
- NaverOCR API 적용
- OCR 인증로직 구현완료
- booth_review_write.jsp views 내로 이동
Fixes : OCR 처리 후 전달 중 Null값 발생오류 fix중
=> Feat: "OCR활용 영수증 인증기능 일부 구현"

src/main/java/com/multi/FM/users/UsersController.java, src/main/webapp/users/signup_cus.jsp, src/main/webapp/users/signup_seller.jsp, src/main/webapp/users/signup_type.jsp
=> Fix : "js코드 수정"

src/main/webapp/WEB-INF/views/mypage/mypage_edit_info.jsp, src/main/webapp/resources/js/mypage_edit.js
=> Fix : "체크 표시 개선"

src/main/java/com/multi/FM/fstv/FestivalConfiguration.java, src/main/java/com/multi/FM/fstv/FestivalController.java, src/main/java/com/multi/FM/fstv/FestivalDAO.java, src/main/java/com/multi/FM/fstv/FestivalPageVO.java, src/main/java/com/multi/FM/fstv/FestivalService.java, src/main/java/com/multi/FM/fstv/PropertiesReader.java, src/main/java/com/multi/FM/fstv/fstvGetApi.java, src/main/resources/mapper/festival.xml, src/main/webapp/WEB-INF/views/fstv/fstv_detail.jsp, src/main/webapp/fstv_map.jsp, src/main/webapp/manager/admin_header.jsp, src/main/webapp/resources/js/admin_header.js
Feat: "Tour API 축제 데이터 업데이트 기능 구현"
Fix: "fstvGetAPI 싱글톤 api key 분리"
Refactor: "코드 컨벤션 및 불필요한 코드 수정"
=> Feat: "Tour API 축제 데이터 업데이트 기능 구현"

src/main/java/com/multi/FM/review/BoothReviewContoller.java, src/main/java/com/multi/FM/review/BoothReviewDAO.java, src/main/java/com/multi/FM/review/BoothReviewService.java, src/main/java/com/multi/FM/review/BoothReviewVO.java, src/main/resources/mapper/boothMapper.xml, src/main/webapp/WEB-INF/views/booth/booth_detail.jsp, src/main/webapp/WEB-INF/views/review/booth_review.jsp, src/main/webapp/WEB-INF/views/review/booth_review_write.jsp, src/main/webapp/resources/js/booth_detail.js, src/main/webapp/resources/js/booth_review_write.js
- OCR인증 후 review starPoint / keyWord insert 구현 완료
- review_write jsp 수정 -booth_name 클릭 시 발생한 404 error fix
Fixes : booth seller와 selling_number 일치 여부 확인 로직 error 수정중
=> Feat: "review insert 기능 구현완료"

src/main/webapp/resources/js/find_num.js, src/main/webapp/resources/js/new_pw.js, src/main/webapp/resources/js/signup_cus.js, src/main/webapp/resources/js/signup_num.js, src/main/webapp/resources/js/signup_seller.js
=> Refactor : "자바스크립트 코드 리팩토링"

src/main/java/com/multi/FM/fstv/FestivalController.java, src/main/resources/mapper/manager.xml, src/main/webapp/WEB-INF/views/manager/ask_detail.jsp, src/main/webapp/WEB-INF/views/manager/user_detail.jsp, src/main/webapp/cs_ask.jsp
Fix: "Admin 페이지 버그 수정"
Fix: "fstv_detail 리팩토링으로 인한 경로오류 수정"
=> Fix: "Admin 페이지 버그 수정"

src/main/java/com/multi/FM/manager/AskVO.java, src/main/java/com/multi/FM/manager/ManagerController.java, src/main/java/com/multi/FM/manager/ManagerDAO.java, src/main/java/com/multi/FM/manager/ManagerService.java, src/main/java/com/multi/FM/manager/PagingVO.java, src/main/java/com/multi/FM/manager/ReportVO.java, src/main/resources/mapper/manager.xml, src/main/webapp/WEB-INF/views/manager/ask_list.jsp, src/main/webapp/WEB-INF/views/manager/booth_list.jsp, src/main/webapp/WEB-INF/views/manager/delete_booth.jsp, src/main/webapp/WEB-INF/views/manager/report_list.jsp, src/main/webapp/WEB-INF/views/manager/user_detail.jsp, src/main/webapp/WEB-INF/views/manager/user_list.jsp, src/main/webapp/WEB-INF/views/mypage/mypage_ask.jsp, src/main/webapp/WEB-INF/views/mypage/mypage_booth_edit.jsp, src/main/webapp/WEB-INF/views/mypage/mypage_review.jsp, src/main/webapp/WEB-INF/views/review/booth_review.jsp, src/main/webapp/resources/css/ask_detail.css, src/main/webapp/resources/css/booth_detail.css, src/main/webapp/resources/css/booth_review.css, src/main/webapp/resources/css/main.css, src/main/webapp/resources/css/mypage_ask.css, src/main/webapp/resources/css/mypage_booth_add.css, src/main/webapp/resources/css/mypage_review.css, src/main/webapp/resources/css/report_detail.css, src/main/webapp/resources/css/user_list.css
=> Fix: "page 오류 수정"

src/main/java/com/multi/FM/review/BoothReviewContoller.java, src/main/java/com/multi/FM/review/NaverOCR.java, src/main/java/com/multi/FM/review/ReceiptDAO.java, src/main/java/com/multi/FM/review/ReceiptService.java, src/main/java/com/multi/FM/review/ReceiptVO.java, src/main/resources/mapper/boothMapper.xml, src/main/webapp/WEB-INF/views/review/booth_review.jsp, src/main/webapp/resources/js/booth_detail.js, src/main/webapp/resources/js/booth_review_write.js
영수증 내 사업자번호와 부스 판매자 사업자번호 일치하는지 확인하는 기능 구현완료
OCR 인증 후 데이터 가공 로직 일부 리팩토링
=> Feat : "영수증 사업자번호 매칭 인증기능 구현"

src/main/java/com/multi/FM/manager/ManagerController.java, src/main/java/com/multi/FM/manager/ManagerDAO.java, src/main/java/com/multi/FM/manager/ManagerService.java, src/main/resources/mapper/managerMapper.xml, src/main/webapp/WEB-INF/views/manager/booth_list.jsp, src/main/webapp/WEB-INF/views/manager/report_checked.jsp, src/main/webapp/WEB-INF/views/manager/report_detail.jsp, src/main/webapp/WEB-INF/views/manager/user_list.jsp, src/main/webapp/WEB-INF/views/mypage/mypage_ask.jsp, src/main/webapp/cs_question.jsp, src/main/webapp/resources/css/ask_detail.css, src/main/webapp/resources/css/cs_question.css, src/main/webapp/resources/css/main.css, src/main/webapp/resources/css/mypage_ask_detail.css, src/main/webapp/resources/css/report_detail.css
=> Fix: "부스 신고 오류 수정"

src/main/resources/mapper/users.xml, src/main/webapp/users/login.jsp
=> Refactor : "필요없는 코드 삭제"

src/main/webapp/resources/js/find_num.js, src/main/webapp/resources/js/mypage_booth_edit.js
=> Fix : "js 코드 수정"

src/main/java/com/multi/FM/myboothpage/MyBoothController.java, src/main/webapp/WEB-INF/views/mypage/mypage_review.jsp, src/main/webapp/resources/css/mypage_review.css, src/main/webapp/resources/css/signup.css, src/main/webapp/resources/js/find_num.js, src/main/webapp/resources/js/main.js, src/main/webapp/resources/js/mypage_booth_add.js, src/main/webapp/resources/js/mypage_booth_edit.js, src/main/webapp/users/signup_seller.jsp
- 마이페이지 부스 등록, 수정 시 user_id 인식못하던 js 수정
- 마이페이지 리뷰, 회원가입 css 수정
- 메인페이지 js 오류코드 주석처리
- sts 콘솔 메시지 출력코드 삭제
=> Fix: "시연 전 전체적인 코드 수정 및 버그 픽스"

src/main/webapp/resources/css/main.css
=> Add: "main.css 수정"

src/main/java/com/multi/FM/mypage/MypageController.java, src/main/java/com/multi/FM/users/UsersController.java, src/main/java/com/multi/FM/users/UsersDAO.java, src/main/resources/mapper/users.xml
=> Add : "db password 암호화"
